version: "3"

services:
  web:
    container_name: evident
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./:/Demo/
    depends_on:
      - db
  db:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=evident1
    ports:
      - 5434:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  


